INSERT INTO `states` (`number_id`, `name`, `abbrev`, `country`) VALUES
(1, 'Aguascalientes', '', 'MX'),
(2, 'Baja California', '', 'MX'),
(3, 'Baja California Sur', '', 'MX'),
(4, 'Campeche', '', 'MX'),
(5, 'Coahuila de Zaragoza', '', 'MX'),
(6, 'Colima', '', 'MX'),
(7, 'Chiapas', '', 'MX'),
(8, 'Chihuahua', '', 'MX'),
(9, 'Distrito Federal', '', 'MX'),
(10, 'Durango', '', 'MX'),
(11, 'Guanajuato', '', 'MX'),
(12, 'Guerrero', '', 'MX'),
(13, 'Hidalgo', '', 'MX'),
(14, 'Jalisco', '', 'MX'),
(15, 'México', '', 'MX'),
(16, 'Michoacán de Ocampo', '', 'MX'),
(17, 'Morelos', '', 'MX'),
(18, 'Nayarit', '', 'MX'),
(19, 'Nuevo León', '', 'MX'),
(20, 'Oaxaca de Juárez', '', 'MX'),
(21, 'Puebla', '', 'MX'),
(22, 'Querétaro', '', 'MX'),
(23, 'Quintana Roo', '', 'MX'),
(24, 'San Luis Potosí', '', 'MX'),
(25, 'Sinaloa', '', 'MX'),
(26, 'Sonora', '', 'MX'),
(27, 'Tabasco', '', 'MX'),
(28, 'Tamaulipas', '', 'MX'),
(29, 'Tlaxcala', '', 'MX'),
(30, 'Veracruz de Ignacio de la Llave', '', 'MX'),
(31, 'Yucatán', '', 'MX'),
(32, 'Zacatecas', '', 'MX');